### ISSUE TITLE
Reading other tags

### ISSUE THREAD

**Issue by lpil** [mrkkrp/htaglib#6]
Hello!

I'm looking to read tags from my music collection, and this library looks really nice, thank you for this :)

I was wondering if it would be possible to use this library to read other tags (such as `LABEL` or `BPM`), or whether I would need to look elsewhere.

I'm looking to work primarily with FLAC, though I'd like to support other formats too.

Cheers,
Louis

**Comment by mrkkrp** [comment]
I'm afraid with this one you won't be able to read other tags because the C API of TagLib consists of a fixed set per-tag functions such as `taglib_tag_title`, `taglib_tag_set_title`.

For FLAC I have a wrapper around libFLAC---reference implementation of FLAC:

https://github.com/mrkkrp/flac

It allows to work with more tags, but still for the sake of safety the tags are modelled as a sum type. If you run into problems with that we can either extend the type to include things like `LABEL` or `BPM`, or to add a constructor like `Custom Text` which would allow to manipulate arbitrary tags.

See: https://hackage.haskell.org/package/flac-0.1.2/docs/Codec-Audio-FLAC-Metadata.html#t:VorbisField for currently supported tags.

**Comment by lpil** [comment]
Would you accept a PR adding additional fields to your flac library?

Do you know of any libraries that would allow me to read other tags from other formats? :)

Thank you.

**Comment by mrkkrp** [comment]
> Would you accept a PR adding additional fields to your flac library?

Yes, certainly. BTW, I think `LABEL` is already there as `Organization`. [This page](https://www.xiph.org/vorbis/doc/v-comment.html) may be of interest. Before adding new tags make sure that they are at least semi-standard (i.e. commonly used).

> Do you know of any libraries that would allow me to read other tags from other formats? :)

Well, I also have a lame LAME binding here:

https://www.stackage.org/haddock/nightly-2017-08-25/lame-0.1.1/Codec-Audio-LAME.html

But the set of tags it supports is also limited, although unlike TagLib it can be extended, see:

https://github.com/mrkkrp/lame/blob/master/Codec/Audio/LAME.hs#L255-L262

These magic strings `"TIT2"`, etc. allow to select tag to overwrite. There is a table of these identifiers somewhere on the net.

**Comment by lpil** [comment]
I've been working off this table for tags: http://wiki.hydrogenaud.io/index.php?title=Tag_Mapping

I think your suggestion of `Organisation` is better though, I'll edit my media to use that.

Great, I feel I have enough to continue. Thank you for your help!
